########################################################################
# Este arquivo docker-compose faz uso das imagens originais, 
# personalizadas por meio dos Dockerfile.
#
# Para inicializar os contêiners utilizando este aquivo, estando no 
# diretório no qual este arquivo se localiza, basta executar:
#
# docker compose up --build (o --build caso queira construir as imagens)
# 
# docker compose build <container> (se deseja build imagem especifica)
# docker compose up
#
########################################################################
services:
  db:
    build: ./db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: ./web
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  monitor:
    build: ./monitor
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
      - db